=== mohamedbentaleb02/XML/cv.dtd
<!ELEMENT cv (informations_personnelles, diplomes, domaines_competence, experiences_professionnelles, langues, loisirs)>

<!ELEMENT informations_personnelles (nom, prenom, sexe, date_naissance, contact)>
<!ELEMENT nom (#PCDATA)>
<!ELEMENT prenom (#PCDATA)>
<!ELEMENT sexe (#PCDATA)>
<!ELEMENT date_naissance (jour, mois, annee)>
<!ELEMENT jour (#PCDATA)>
<!ELEMENT mois (#PCDATA)>
<!ELEMENT annee (#PCDATA)>
<!ELEMENT contact (adresse, telephone, mail)>
<!ELEMENT adresse (#PCDATA)>
<!ELEMENT telephone (#PCDATA)>
<!ELEMENT mail (#PCDATA)>

<!ELEMENT diplomes (diplome+)>
<!ELEMENT diplome (designation, date, affiliation, serie, mention?)>
<!ELEMENT designation (#PCDATA)>
<!ELEMENT date (#PCDATA)>
<!ELEMENT affiliation (#PCDATA)>
<!ELEMENT serie (#PCDATA)>
<!ELEMENT mention (#PCDATA)>

<!ELEMENT domaines_competence (domaine*)>
<!ELEMENT domaine (intitule, niveau, description)>
<!ELEMENT intitule (#PCDATA)>
<!ELEMENT niveau (#PCDATA)>
<!ELEMENT description (#PCDATA)>

<!ELEMENT experiences_professionnelles (experience*)>
<!ELEMENT experience (designation, date_debut, date_fin, affiliation, mission)>
<!ATTLIST experience type CDATA #REQUIRED> <!ELEMENT date_debut (#PCDATA)>
<!ELEMENT date_fin (#PCDATA)>
<!ELEMENT mission (#PCDATA)>

<!ELEMENT langues (langue*)>
<!ELEMENT langue (#PCDATA)>
<!ATTLIST langue niveau (Scolaire|Moyen|Courant|Bilingue) "Moyen"> <!ELEMENT loisirs (loisir*)>
<!ELEMENT loisir (#PCDATA)>

=== mohamedbentaleb02/XML/cv.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE cv SYSTEM "cv.dtd">
<cv>
    <informations_personnelles>
        <nom>BEN TALEB</nom>
        <prenom>Mohamed</prenom>
        <sexe>M</sexe>
        <date_naissance>
            <jour>02</jour>
            <mois>03</mois>
            <annee>2002</annee>
        </date_naissance>
        <contact>
            <adresse>Agadir, Maroc</adresse>
            <telephone>0637540371</telephone>
            <mail>mohamedbentaleb@gmail.com</mail>
        </contact>
    </informations_personnelles>

    <diplomes>
        <diplome>
            <designation>Ingénieur d'état</designation>
            <date>2025</date>
            <affiliation>SupMti Rabat</affiliation>
            <serie>IT</serie>
            <mention>Très Bien</mention>
        </diplome>
    </diplomes>

    <domaines_competence>
        <domaine>
            <intitule>Technologies DotNet</intitule>
            <niveau>Expert</niveau>
            <description>c#, RabbitMQ, Clean architecture, Entity Framework, OAuth2</description>
        </domaine>
    </domaines_competence>

    <experiences_professionnelles>
        <experience type="Travail">
            <designation>.NET Developer</designation>
            <date_debut>2023</date_debut>
            <date_fin>Aujourd'hui</date_fin>
            <affiliation>ACG</affiliation>
            <mission>Consultant IT</mission>
        </experience>
    </experiences_professionnelles>

    <langues>
        <langue niveau="Courant">Français</langue>
        <langue niveau="Moyen">Anglais</langue>
    </langues>

    <loisirs>
        <loisir>Football</loisir>
        <loisir>Voyage</loisir>
    </loisirs>
</cv>
